### ISSUE TITLE
Does RiseML server store my code?

### ISSUE THREAD

**Issue by soloman817** [riseml/riseml#5]
Hi, I'm evaluating RiseML. In the doc, it says: "It reads the configuration file (riseml.yml by default) and automatically synchronizes the project directory to RiseML, where it is stored in a version control system.".  Does that mean RiseML has its own VCS and our source code (the whole project) has to be pushed to RiseML server? If so, is that public or private accessible?

**Comment by elmarhaussmann** [comment]
Yes, RiseML has its own VCS. You don't have to push any code manually, the `riseml train` command synchronizes your project folder automatically each time you run it.

The VCS inside RiseML is not publicly accessible. It is running on the cluster where you installed RiseML and no code is sent outside the cluster.

I hope that answers your questions. Let me know if you have further questions.
